name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Run Tests
      run: cargo test --release
    - name: Upload Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        # Artifact name
        name: rust-web
        path: target/release/rust-web
