name: CI-CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  CI:
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        clean: false
    - name: Build
      run: cargo build --release --verbose
    - name: Tests
      run: cargo test --release --verbose
    - name: Upload Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: rust-web
        path: target/release/rust-web
        
  CD:
    runs-on: self-hosted
    needs: CI
    steps:  
    - name: Stop Service
      run: service web stop
    - name: Download Artifact
      uses: actions/download-artifact@v2.0.9
      with:
        name: rust-web
        path: /usr/local/app
    - name: Start Service
      run: service web start
