name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  checkout:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        clean: false

  build:
    runs-on: self-hosted
    steps:
    - name: Build
      run: cargo build --release --verbose
      
  test:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Run Tests
      run: cargo test --release --verbose
      
  artifact:
    runs-on: self-hosted
    needs: test
    steps:  
    - name: Upload Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: rust-web
        path: target/release/rust-web
